# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portland Ruby Brigade
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Also known as pdxruby and pdx.rb, is a user group for Ruby programmers in the Portland, Oregon area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pdxruby.org" # the base hostname & protocol for your site
twitter_username: pdxruby
github:
  repo: https://github.com/pdxruby/pdxruby.github.io

# Build settings
markdown: kramdown
timezone: "America/Los_Angeles"

gems:
  - jekyll-gist
