# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Portland Ruby Brigade, also known as pdxruby and pdx.rb,
  is a user group for Ruby programmers in the Portland, Oregon area.
  The group welcomes all programmers interested in the language
  and its implementations, tools, libraries and frameworks, such
  as Ruby on Rails. The group has been meeting since August 2002
  for presentations, demos and discussions applicable to all skill
  levels, from newbies and experts. Every month 100+ people
  come together to share their knowledge, projects and enthusiasm
  for Ruby – join us!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pdxruby.org" # the base hostname & protocol for your site
twitter_username: pdxruby
github_username:  pdxruby

# Build settings
markdown: kramdown
timezone: "America/Los_Angeles"

gems:
  - jekyll-gist
